collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3195489
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#033003'
    - '#547730'
    - '#A39A5C'
  rhythmicContrast: 1
typography_spectrum: 0.3786251
layout_spectrum: 0.5698174
name: 'Grassy Hill Photography '
