layout_spectrum: 0.5053706
typography_spectrum: 0.1170247
color:
  saturation: 0.5075188
  lightness: 0.4119226
  brandStrength: 0.6267455
  brandColors:
    - '#033003'
    - '#547730'
    - '#A39A5C'
  rhythmicContrast: 0.5601504
name: 'Grassy Hill Photography '
